import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.min.css';
import 'semantic-ui-css/semantic.min.css'
import 'font-awesome/css/font-awesome.min.css';
import 'toastr/build/toastr.min.css';
import '../styles/globals.css';
import { cookies } from 'next/headers';


// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const cookieStore = cookies();
  const cookieValue = cookieStore.get('isToggle')?.value;
  
  const toggleClass = cookieValue == 'true' ? 'sidenav-toggled':'';
    return (
        <html lang='en'>
            {/* <body  className={inter.className}>{children}</body> */}
            <body  className={`app sidebar-mini ${toggleClass}`}>{children}</body>
        </html>
    );
}
